#!/bin/sh
# Useage: ./load3518_stage2 [ sensor ]
#

detect_ar0130()
{
    sensor_id=`i2c_read 0x20 0x3000 0x3000 2 2 | grep ^0x3000 | awk '{print $2}'`
    if [ "x${sensor_id}" = "x0x2402" ]; then
	echo "...sensor AR0130 detected..."
	exit
    fi
}

detect_ar0331()
{
    sensor_id=`i2c_read 0x20 0x3000 0x3000 2 2 | grep ^0x3000 | awk '{print $2}'`
    if [ "x${sensor_id}" = "x0x2602" ]; then
	echo "...sensor AR0331 detected..."
	exit
    fi
}

detect_nt99141()
{
    exit
}

load_usage()
{
    echo "Usage:  ./load3518_stage2 [sensor_name]"
    echo -e "Available sensors: AR0130, AR0331, NT99141"
    echo -e "for example: ./load3518_stage2 AR0130 \n"
}

# load module.
if [ $# -eq 0 ]
then
    detect_ar0130
    detect_ar0331
    detect_nt99141
    exit
fi

if [ $# -g 0 ]
then
    export SENSOR_TYPE=$1
fi
